app/Http/routes.php
<?php

Route::group(['prefix' => LaravelLocalization::setLocale()], function () {

    Route::group(['prefix' => 'auth'], function () {
        Route::get('login', 'Auth\AuthController@getLogin');
        Route::post('login', 'Auth\AuthController@postLogin');
        Route::get('logout', 'Auth\AuthController@getLogout');
    });

    Route::group(['prefix' => 'betting', 'middleware' => 'auth', 'as' => 'betting.'], function () {
//    Route::get('login'  , ['as' => 'login', 'uses' => 'SecurityController@login']);
//    Route::get('logout'  , ['as' => 'logout', 'uses' => 'SecurityController@logout']);
//    Route::post('check'  , ['as' => 'check', 'uses' => 'SecurityController@check']);
//    Route::get('index'  , ['as' => 'index', 'middleware'=>'security:ROLE_ADMIN', 'uses' => 'DefaultController@index']);
//    Route::get('update2'  , ['as' => 'update2', 'middleware'=>'security:ROLE_ADMIN', 'uses' => 'DefaultController@update2']);

        Route::get('index'  , ['as' => 'index', 'uses' => 'DefaultController@index']);

        //Rotas para Dashboard
        Route::post('dashboard'  , ['as' => 'dashboard', 'uses' => 'DefaultController@dashboard']);
        Route::post('resultVendas'  , ['as' => 'resultVendas', 'uses' => 'DefaultController@resultadosVendas']);

        //Rotas para sete da sorte
        Route::get('seteSorte'  , ['as' => 'seteSorte', 'uses' => 'SeteSorteController@index']);
        Route::post('seteGrid'  , ['as' => 'seteGrid', 'uses' => 'SeteSorteController@dashboard']);
        Route::post('resultVendasST'  , ['as' => 'resultVendasST', 'uses' => 'SeteSorteController@resultadosVendas']);

        //Rotas para selectes via ajax
        Route::post('allTipoCotacao'  , ['as' => 'allTipoCotacao', 'uses' => 'DefaultController@allTipoCotacao']);

        Route::group(['prefix' => 'parametro', 'as' => 'parametro.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'ParametrosController@index']);
            Route::get('grid', ['as' => 'grid', 'uses' => 'ParametrosController@grid']);
            Route::get('create', ['as' => 'create', 'uses' => 'ParametrosController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'ParametrosController@store']);
            Route::get('save', ['middleware' => 'permission:parametro.update', 'as' => 'save', 'uses' => 'ParametrosController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'ParametrosController@update']);
        });

        Route::group(['prefix' => 'area', 'as' => 'area.'], function () {
            Route::get('index', ['middleware' => 'permission:area.select', 'as' => 'index', 'uses' => 'AreasController@index']);
            Route::post('grid', ['as' => 'grid', 'uses' => 'AreasController@grid']);
            Route::get('create', ['middleware' => 'permission:area.create', 'as' => 'create', 'uses' => 'AreasController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'AreasController@store']);
            Route::get('edit/{id}', ['middleware' => 'permission:area.update', 'as' => 'edit', 'uses' => 'AreasController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'AreasController@update']);
            Route::get('delete/{id}', ['middleware' => 'permission:area.destroy', 'as' => 'delete', 'uses' => 'AreasController@delete']);
        });

        Route::group(['prefix' => 'vendedor', 'as' => 'vendedor.'], function () {
            Route::get('index', ['middleware' => 'permission:vendedor.select', 'as' => 'index', 'uses' => 'VendedorController@index']);
            Route::post('grid', ['as' => 'grid', 'uses' => 'VendedorController@grid']);
            Route::post('gridConfig/{id}', ['as' => 'gridConfig', 'uses' => 'VendedorController@gridConfig']);
            Route::get('create', ['middleware' => 'permission:vendedor.create', 'as' => 'create', 'uses' => 'VendedorController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'VendedorController@store']);
            Route::post('storeConfig', ['as' => 'storeConfig', 'uses' => 'VendedorController@storeConfig']);
            Route::get('edit/{id}', ['middleware' => 'permission:vendedor.update', 'as' => 'edit', 'uses' => 'VendedorController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'VendedorController@update']);
            Route::post('updateConfig', ['as' => 'updateConfig', 'uses' => 'VendedorController@updateConfig']);
            Route::get('zerar/{id}', ['as' => 'zerar', 'uses' => 'VendedorController@zerar']);
        });

        Route::group(['prefix' => 'arrecadador', 'as' => 'arrecadador.'], function () {
            Route::get('index', ['middleware' => 'permission:arrecadador.select', 'as' => 'index', 'uses' => 'ArrecadadorController@index']);
            Route::post('grid', ['as' => 'grid', 'uses' => 'ArrecadadorController@grid']);
            Route::get('create', ['middleware' => 'permission:arrecadador.create', 'as' => 'create', 'uses' => 'ArrecadadorController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'ArrecadadorController@store']);
            Route::get('edit/{id}', ['middleware' => 'permission:arrecadador.update', 'as' => 'edit', 'uses' => 'ArrecadadorController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'ArrecadadorController@update']);
            Route::get('delete/{id}', ['middleware' => 'permission:arrecadador.destroy', 'as' => 'delete', 'uses' => 'ArrecadadorController@delete']);
        });

        # Rota para as partidas
        Route::group(['prefix' => 'partidas', 'as' => 'partidas.'], function () {
            Route::get('index', ['middleware' => 'permission:partida.select', 'as' => 'index', 'uses' => 'PartidasController@index']);
            Route::post('grid', ['as' => 'grid', 'uses' => 'PartidasController@grid']);
            Route::get('create', ['middleware' => 'permission:partida.create', 'as' => 'create', 'uses' => 'PartidasController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'PartidasController@store']);
            Route::get('edit/{id}', ['middleware' => 'permission:partida.update', 'as' => 'edit', 'uses' => 'PartidasController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'PartidasController@update']);
            Route::get('destroy/{id}', ['middleware' => 'permission:partida.destroy', 'as' => 'edit', 'uses' => 'PartidasController@destroy']);
            Route::get('getPartidas', ['as' => 'getPartidas', 'uses' => 'PartidasController@getPartidas']);
            Route::get('getPartidasSemApostas', ['as' => 'getPartidasSemApostas', 'uses' => 'PartidasController@getPartidasSemApostas']);
        });

        # Rota para as modalidades
        Route::group(['prefix' => 'modalidades', 'as' => 'modalidades.'], function () {
            Route::get('index', ['middleware' => 'permission:modalidade.select', 'as' => 'index', 'uses' => 'ModalidadesController@index']);
            Route::post('grid', ['as' => 'grid', 'uses' => 'ModalidadesController@grid']);
            Route::get('create', ['middleware' => 'permission:modalidade.create', 'as' => 'create', 'uses' => 'ModalidadesController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'ModalidadesController@store']);
            Route::get('edit/{id}', ['middleware' => 'permission:modalidade.update', 'as' => 'edit', 'uses' => 'ModalidadesController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'ModalidadesController@update']);
            Route::get('destroy/{id}', ['middleware' => 'permission:modalidade.destroy', 'as' => 'edit', 'uses' => 'ModalidadesController@destroy']);
            Route::get('getModalidade/{id}', ['as' => 'getModalidade', 'uses' => 'ModalidadesController@getModalidade']);
        });

        # Rota para as cotações
        Route::group(['prefix' => 'cotacoes', 'as' => 'cotacoes.'], function () {
            Route::get('index', ['middleware' => 'permission:cotacao.select', 'as' => 'index', 'uses' => 'CotacoesController@index']);
            Route::post('grid', ['as' => 'grid', 'uses' => 'CotacoesController@grid']);
            Route::get('create', ['middleware' => 'permission:cotacao.create', 'as' => 'create', 'uses' => 'CotacoesController@create']);
            Route::get('createMultiplo', ['as' => 'createMultiplo', 'uses' => 'CotacoesController@createMultiplo']);
            Route::post('store', ['as' => 'store', 'uses' => 'CotacoesController@store']);
            Route::post('storeMultiplo', ['as' => 'storeMultiplo', 'uses' => 'CotacoesController@storeMultiplo']);
            Route::get('edit/{id}', ['middleware' => 'permission:cotacao.update', 'as' => 'edit', 'uses' => 'CotacoesController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'CotacoesController@update']);
            Route::get('destroy/{id}', ['middleware' => 'permission:cotacao.destroy', 'as' => 'edit', 'uses' => 'CotacoesController@destroy']);
        });

        # Rota para gols
        Route::group(['prefix' => 'gols', 'as' => 'gols.'], function () {
            Route::get('index', ['middleware' => 'permission:resultado.select', 'as' => 'index', 'uses' => 'GolsController@index']);
            Route::post('grid/{idPartida}', ['as' => 'grid', 'uses' => 'GolsController@grid']);
            Route::get('create', ['as' => 'create', 'uses' => 'GolsController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'GolsController@store']);
            Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'GolsController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'GolsController@update']);
            Route::delete('delete/{id}', ['as' => 'delete', 'uses' => 'GolsController@destroy']);
            Route::get('getTimes', ['as' => 'getTimes', 'uses' => 'GolsController@getTimes']);

app/Http/Controllers/AreasController.php
<?php

namespace Softage\Http\Controllers;

use Illuminate\Http\Request;

use Illuminate\Support\Facades\Auth;
use Softage\Services\AreaService;
use Softage\Http\Requests;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;
use Softage\Http\Requests\AreasCreateRequest;
use Softage\Http\Requests\AreasUpdateRequest;
use Softage\Validators\AreasValidator;
use Yajra\Datatables\Datatables;


class AreasController extends Controller
{
    
    /**
     * @var AreaService
     */
    private $service;

    /**
     * @var AreasValidator
     */
    private $validator;

    /**
     * @var array
     */
    private $loadFields = [
    ];

    public function __construct(AreaService $service, AreasValidator $validator)
    {
        $this->service = $service;
        $this->validator = $validator;
    }


    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('area.index');
    }

    /**
     * @return mixed
     */
    public function grid()
    {
        #Criando a consulta
        $rows = \DB::table('areas')->select(['id', 'nome']);

        #Editando a grid
        return Datatables::of($rows)->addColumn('action', function ($row) {
            $html = "";

            # Recuperando o usuário;
            $user = Auth::user();

            # Checando permissão
            if($user->can('area.update')) {
                $html .= '<a href="edit/'.$row->id.'" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Editar</a> ';
            }

            # Verificando se existe vinculo com o currículo
            $area = $this->service->find($row->id);

            if(count($area->vendedores) == 0) {
                if($user->can('area.destroy')) {
                    $html .= '<a href="delete/'.$row->id.'" class="btn btn-xs btn-danger delete"><i class="glyphicon glyphicon-edit"></i> Deletar</a>';
                }
            }
            return $html;
        })->make(true);
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        #Carregando os dados para o cadastro
        $loadFields = $this->service->load($this->loadFields);

        #Retorno para view
        return view('area.create', compact('loadFields'));
    }

    /**
     * @param Request $request
     * @return $this|array|\Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        try {
            #Recuperando os dados da requisição
            $data = $request->all();

            #Validando a requisição
            $this->validator->with($data)->passesOrFail(ValidatorInterface::RULE_CREATE);

            #Executando a ação
            $this->service->store($data);

            #Retorno para a view
            return redirect()->back()->with("message", "Cadastro realizado com sucesso!");
        } catch (ValidatorException $e) {
            return redirect()->back()->withErrors($this->validator->errors())->withInput();
        } catch (\Throwable $e) {print_r($e->getMessage()); exit;
            return redirect()->back()->with('message', $e->getMessage());
        }
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\RedirectResponse|\Illuminate\View\View
     */
    public function edit($id)
    {
        try {
            #Recuperando a empresa
            $model = $this->service->find($id);

            #Tratando as datas
            // $aluno = $this->service->getAlunoWithDateFormatPtBr($aluno);

            #Carregando os dados para o cadastro
            $loadFields = $this->service->load($this->loadFields);

            #retorno para view
            return view('area.edit', compact('model', 'loadFields'));
        } catch (\Throwable $e) {dd($e);
            return redirect()->back()->with('message', $e->getMessage());
        }
    }

    /**
     * @param Request $request
     * @param $id
     * @return $this|\Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        try {
            #Recuperando os dados da requisição
            $data = $request->all();

            #tratando as rules
            $this->validator->replaceRules(ValidatorInterface::RULE_UPDATE, ":id", $id);

            #Validando a requisição
            $this->validator->with($data)->passesOrFail(ValidatorInterface::RULE_UPDATE);

            #Executando a ação
            $this->service->update($data, $id);

            #Retorno para a view
            return redirect()->back()->with("message", "Alteração realizada com sucesso!");
        } catch (ValidatorException $e) {
            return redirect()->back()->withErrors($this->validator->errors())->withInput();
        } catch (\Throwable $e) { dd($e);
            return redirect()->back()->with('message', $e->getMessage());
        }
    }

    /**
     * @param Request $request
     * @param $id
     */
    public function delete($id)
    {
        try {
            #Executando a ação
            $this->service->delete($id);

            #Retorno para a view
            return redirect()->back()->with("message", "Remoção realizada com sucesso!");
        } catch (\Throwable $e) { dd($e);
            return redirect()->back()->with('message', $e->getMessage());
        }
    }
}

resources/views/area/create.blade.php
@extends('menu')

@section('css')
    @parent
    <style>
        .form-group {
            margin-top: -10px;;
        }
    </style>
@endsection

@section('page-heading')
    <h1>Área</h1>
@endsection

@section('container')

    <div data-widget-group="group1">
        <div class="row">
            <div class="col-sm-12">

                @if(Session::has('message'))
                    <div class="alert alert-success">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <em> {!! session('message') !!}</em>
                    </div>
                @endif

                @if(Session::has('errors'))
                    <div class="alert alert-danger">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        @foreach($errors->all() as $error)
                            <div>{{ $error }}</div>
                        @endforeach
                    </div>
                @endif

                <div class="panel panel-default" data-widget='{"draggable": "false"}'>
                    <div class="panel-heading">
                        <h2>Cadastrar área</h2>
                        <div class="panel-ctrls" data-actions-container=""
                             data-action-collapse='{"target": ".panel-body"}'></div>
                    </div>
                    {!! Form::open(['route'=>'betting.area.store', 'method' => "POST", 'id' => 'formArea', 'class' => 'form-horizontal row-border','enctype' => 'multipart/form-data']) !!}
                    <div class="panel-body">
                        @include('tamplatesForms.tamplateFormArea')
                    </div>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-sm-8 col-sm-offset-2">
                                <button type="submit" class="btn-primary btn" style="margin-left: -11px">Salvar</button>
                                <a class="btn-default btn" href="{{ route('betting.area.index')}}">Voltar</a>
                            </div>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/area/edit.blade.php
@extends('menu')

@section('css')
    @parent
    <style>
        .form-group {
            margin-top: -10px;;
        }
    </style>
@endsection

@section('page-heading')
    <h1>Área</h1>
@endsection

@section('container')

    <div data-widget-group="group1">
        <div class="row">
            <div class="col-sm-12">

                @if(Session::has('message'))
                    <div class="alert alert-success">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <em> {!! session('message') !!}</em>
                    </div>
                @endif

                @if(Session::has('errors'))
                    <div class="alert alert-danger">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        @foreach($errors->all() as $error)
                            <div>{{ $error }}</div>
                        @endforeach
                    </div>
                @endif

                <div class="panel panel-default" data-widget='{"draggable": "false"}'>
                    <div class="panel-heading">
                        <h2>Editar Área</h2>
                        <div class="panel-ctrls" data-actions-container=""
                             data-action-collapse='{"target": ".panel-body"}'></div>
                    </div>

                    {!! Form::model($model, ['route'=> ['betting.area.update', $model->id], 'id' => 'formArea', 'class' => 'form-horizontal row-border','enctype' => 'multipart/form-data']) !!}
                    <div class="panel-body">
                        @include('tamplatesForms.tamplateFormArea')
                    </div>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-sm-8 col-sm-offset-2">
                                <button type="submit" class="btn-primary btn" style="margin-left: -11px">Salvar</button>
                                <a class="btn-default btn" href="{{ route('betting.area.index')}}">Voltar</a>
                            </div>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/area/index.blade.php
@extends('menu')

@section('css')
    @parent
<style>
    .table-responsive {
        min-height: 0.01%;
        overflow-x: initial;
    }
</style>
@endsection

@section('page-heading')
    <h1>Área</h1>
@endsection

@section('container')

    <div data-widget-group="group1">
        <div class="row">
            <div class="col-sm-12">
                @if(Session::has('message'))
                    <div class="alert alert-success">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <em> {!! session('message') !!}</em>
                    </div>
                @endif

                @if(Session::has('errors'))
                    <div class="alert alert-danger">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        @foreach($errors->all() as $error)
                            <div>{{ $error }}</div>
                        @endforeach
                    </div>
                @endif

                <div class="panel panel-default" data-widget='{"draggable": "false"}'>
                    <div class="panel-heading">
                        <h2>Lista de áreas</h2><br />

                        @permission('area.create')
                        <a href="{{ route('betting.area.create')}}" class="btn btn-primary">Nova Área</a>
                        @endpermission

                        <div class="panel-ctrls" data-actions-container=""
                             data-action-collapse='{"target": ".panel-body"}'></div>
                    </div>

                    <div class="panel-body">
                        <div class="table-responsive no-padding">
                            <table id="area-grid" class="display table table-bordered" cellspacing="0" width="100%">
                                <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>Acão</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>Nome</th>
                                    <th style="width: 15%;">Acão</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

@endsection

@section('js')
    @parent
    <script type="text/javascript">

        var table = $('#area-grid').DataTable({
            processing: true,
            serverSide: true,
            ajax: {
                url: "{!! route('betting.area.grid') !!}",
                method: 'POST'
            },
            language: {
                "lengthMenu": "_MENU_",
                "zeroRecords": "Não foram encontrados resultados",
                "info": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                "infoEmpty": "Mostrando de 0 até 0 de 0 registros",
                "infoFiltered": "(Filtrado de _MAX_ total de registro)",
                "sProcessing":   "Processando...",
                "oPaginate": {
                    "sFirst":    "Primeiro",
                    "sPrevious": "Anterior",
                    "sNext":     "Seguinte",
                    "sLast":     "Último"
                }
            },
            columns: [
                {data: 'nome', name: 'nome'},
                {data: 'action', name: 'action', orderable: false, searchable: false}
            ]
        });

        $('.dataTables_filter input').attr('placeholder','Pesquisar...');

        //DOM Manipulation to move datatable elements integrate to panel
        $('.panel-ctrls').append($('.dataTables_filter').addClass("pull-right")).find("label").addClass("panel-ctrls-center");
        $('.panel-ctrls').append("<i class='separator'></i>");
        $('.panel-ctrls').append($('.dataTables_length').addClass("pull-left")).find("label").addClass("panel-ctrls-center");

        $('.panel-footer').append($(".dataTable+.row"));
        $('.dataTables_paginate>ul.pagination').addClass("pull-right m-n");

        $(document).on('click', 'a.delete', function (event) {
            event.preventDefault();
            var url = $(this).attr('href');
            bootbox.confirm("Tem certeza da exclusão do item?", function (result) {
                if (result) {
                    location.href = url
                } else {
                    false;
                }
            });
        });

    </script>
@endsection