app/Http/routes.php
Route::group(['prefix' => LaravelLocalization::setLocale()], function () {

    Route::group(['prefix' => 'auth'], function () {
        Route::get('login', 'Auth\AuthController@getLogin');
        Route::post('login', 'Auth\AuthController@postLogin');
        Route::get('logout', 'Auth\AuthController@getLogout');
    });

    Route::group(['prefix' => 'betting', 'middleware' => 'auth', 'as' => 'betting.'], function () {
//    Route::get('login'  , ['as' => 'login', 'uses' => 'SecurityController@login']);
//    Route::get('logout'  , ['as' => 'logout', 'uses' => 'SecurityController@logout']);
//    Route::post('check'  , ['as' => 'check', 'uses' => 'SecurityController@check']);
//    Route::get('index'  , ['as' => 'index', 'middleware'=>'security:ROLE_ADMIN', 'uses' => 'DefaultController@index']);
//    Route::get('update2'  , ['as' => 'update2', 'middleware'=>'security:ROLE_ADMIN', 'uses' => 'DefaultController@update2']);

        Route::get('index'  , ['as' => 'index', 'uses' => 'DefaultController@index']);

        //Rotas para Dashboard
        Route::post('dashboard'  , ['as' => 'dashboard', 'uses' => 'DefaultController@dashboard']);
        Route::post('resultVendas'  , ['as' => 'resultVendas', 'uses' => 'DefaultController@resultadosVendas']);

        //Rotas para sete da sorte
        Route::get('seteSorte'  , ['as' => 'seteSorte', 'uses' => 'SeteSorteController@index']);
        Route::post('seteGrid'  , ['as' => 'seteGrid', 'uses' => 'SeteSorteController@dashboard']);
        Route::post('resultVendasST'  , ['as' => 'resultVendasST', 'uses' => 'SeteSorteController@resultadosVendas']);

        //Rotas para selectes via ajax
        Route::post('allTipoCotacao'  , ['as' => 'allTipoCotacao', 'uses' => 'DefaultController@allTipoCotacao']);

        Route::group(['prefix' => 'parametro', 'as' => 'parametro.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'ParametrosController@index']);
            Route::get('grid', ['as' => 'grid', 'uses' => 'ParametrosController@grid']);
            Route::get('create', ['as' => 'create', 'uses' => 'ParametrosController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'ParametrosController@store']);
            Route::get('save', ['middleware' => 'permission:parametro.update', 'as' => 'save', 'uses' => 'ParametrosController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'ParametrosController@update']);
        });

        Route::group(['prefix' => 'area', 'as' => 'area.'], function () {
            Route::get('index', ['middleware' => 'permission:area.select', 'as' => 'index', 'uses' => 'AreasController@index']);
            Route::post('grid', ['as' => 'grid', 'uses' => 'AreasController@grid']);
            Route::get('create', ['middleware' => 'permission:area.create', 'as' => 'create', 'uses' => 'AreasController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'AreasController@store']);
            Route::get('edit/{id}', ['middleware' => 'permission:area.update', 'as' => 'edit', 'uses' => 'AreasController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'AreasController@update']);
            Route::get('delete/{id}', ['middleware' => 'permission:area.destroy', 'as' => 'delete', 'uses' => 'AreasController@delete']);
        });

        Route::group(['prefix' => 'vendedor', 'as' => 'vendedor.'], function () {
            Route::get('index', ['middleware' => 'permission:vendedor.select', 'as' => 'index', 'uses' => 'VendedorController@index']);
            Route::post('grid', ['as' => 'grid', 'uses' => 'VendedorController@grid']);
            Route::post('gridConfig/{id}', ['as' => 'gridConfig', 'uses' => 'VendedorController@gridConfig']);
            Route::get('create', ['middleware' => 'permission:vendedor.create', 'as' => 'create', 'uses' => 'VendedorController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'VendedorController@store']);
            Route::post('storeConfig', ['as' => 'storeConfig', 'uses' => 'VendedorController@storeConfig']);
            Route::get('edit/{id}', ['middleware' => 'permission:vendedor.update', 'as' => 'edit', 'uses' => 'VendedorController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'VendedorController@update']);
            Route::post('updateConfig', ['as' => 'updateConfig', 'uses' => 'VendedorController@updateConfig']);
            Route::get('zerar/{id}', ['as' => 'zerar', 'uses' => 'VendedorController@zerar']);
        });

        Route::group(['prefix' => 'arrecadador', 'as' => 'arrecadador.'], function () {
            Route::get('index', ['middleware' => 'permission:arrecadador.select', 'as' => 'index', 'uses' => 'ArrecadadorController@index']);
            Route::post('grid', ['as' => 'grid', 'uses' => 'ArrecadadorController@grid']);
            Route::get('create', ['middleware' => 'permission:arrecadador.create', 'as' => 'create', 'uses' => 'ArrecadadorController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'ArrecadadorController@store']);
            Route::get('edit/{id}', ['middleware' => 'permission:arrecadador.update', 'as' => 'edit', 'uses' => 'ArrecadadorController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'ArrecadadorController@update']);
            Route::get('delete/{id}', ['middleware' => 'permission:arrecadador.destroy', 'as' => 'delete', 'uses' => 'ArrecadadorController@delete']);
        });

        # Rota para as partidas
        Route::group(['prefix' => 'partidas', 'as' => 'partidas.'], function () {
            Route::get('index', ['middleware' => 'permission:partida.select', 'as' => 'index', 'uses' => 'PartidasController@index']);
            Route::post('grid', ['as' => 'grid', 'uses' => 'PartidasController@grid']);
            Route::get('create', ['middleware' => 'permission:partida.create', 'as' => 'create', 'uses' => 'PartidasController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'PartidasController@store']);
            Route::get('edit/{id}', ['middleware' => 'permission:partida.update', 'as' => 'edit', 'uses' => 'PartidasController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'PartidasController@update']);
            Route::get('destroy/{id}', ['middleware' => 'permission:partida.destroy', 'as' => 'edit', 'uses' => 'PartidasController@destroy']);
            Route::get('getPartidas', ['as' => 'getPartidas', 'uses' => 'PartidasController@getPartidas']);
            Route::get('getPartidasSemApostas', ['as' => 'getPartidasSemApostas', 'uses' => 'PartidasController@getPartidasSemApostas']);
        });

        # Rota para as modalidades
        Route::group(['prefix' => 'modalidades', 'as' => 'modalidades.'], function () {
            Route::get('index', ['middleware' => 'permission:modalidade.select', 'as' => 'index', 'uses' => 'ModalidadesController@index']);
            Route::post('grid', ['as' => 'grid', 'uses' => 'ModalidadesController@grid']);
            Route::get('create', ['middleware' => 'permission:modalidade.create', 'as' => 'create', 'uses' => 'ModalidadesController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'ModalidadesController@store']);
            Route::get('edit/{id}', ['middleware' => 'permission:modalidade.update', 'as' => 'edit', 'uses' => 'ModalidadesController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'ModalidadesController@update']);
            Route::get('destroy/{id}', ['middleware' => 'permission:modalidade.destroy', 'as' => 'edit', 'uses' => 'ModalidadesController@destroy']);
            Route::get('getModalidade/{id}', ['as' => 'getModalidade', 'uses' => 'ModalidadesController@getModalidade']);
        });

        # Rota para as cotações
        Route::group(['prefix' => 'cotacoes', 'as' => 'cotacoes.'], function () {
            Route::get('index', ['middleware' => 'permission:cotacao.select', 'as' => 'index', 'uses' => 'CotacoesController@index']);
            Route::post('grid', ['as' => 'grid', 'uses' => 'CotacoesController@grid']);
            Route::get('create', ['middleware' => 'permission:cotacao.create', 'as' => 'create', 'uses' => 'CotacoesController@create']);
            Route::get('createMultiplo', ['as' => 'createMultiplo', 'uses' => 'CotacoesController@createMultiplo']);
            Route::post('store', ['as' => 'store', 'uses' => 'CotacoesController@store']);
            Route::post('storeMultiplo', ['as' => 'storeMultiplo', 'uses' => 'CotacoesController@storeMultiplo']);
            Route::get('edit/{id}', ['middleware' => 'permission:cotacao.update', 'as' => 'edit', 'uses' => 'CotacoesController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'CotacoesController@update']);
            Route::get('destroy/{id}', ['middleware' => 'permission:cotacao.destroy', 'as' => 'edit', 'uses' => 'CotacoesController@destroy']);
        });

        # Rota para gols
        Route::group(['prefix' => 'gols', 'as' => 'gols.'], function () {
            Route::get('index', ['middleware' => 'permission:resultado.select', 'as' => 'index', 'uses' => 'GolsController@index']);
            Route::post('grid/{idPartida}', ['as' => 'grid', 'uses' => 'GolsController@grid']);
            Route::get('create', ['as' => 'create', 'uses' => 'GolsController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'GolsController@store']);
            Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'GolsController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'GolsController@update']);
            Route::delete('delete/{id}', ['as' => 'delete', 'uses' => 'GolsController@destroy']);
            Route::get('getTimes', ['as' => 'getTimes', 'uses' => 'GolsController@getTimes']);

resources/views/vendedor/create.blade.php
@extends('menu')

@section('css')
    @parent
    <style>
        .form-group {
            margin-top: -10px;;
        }
    </style>
@endsection

@section('page-heading')
    <h1>Vendedores</h1>
@endsection

@section('container')

    <div data-widget-group="group1">
        <div class="row">
            <div class="col-sm-12">

                @if(Session::has('message'))
                    <div class="alert alert-success">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <em> {!! session('message') !!}</em>
                    </div>
                @endif

                @if(Session::has('errors'))
                    <div class="alert alert-danger">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        @foreach($errors->all() as $error)
                            <div>{{ $error }}</div>
                        @endforeach
                    </div>
                @endif

                <div class="panel panel-default" data-widget='{"draggable": "false"}'>
                    <div class="panel-heading">
                        <h2>Cadastrar vendedor</h2>
                        <div class="panel-ctrls" data-actions-container=""
                             data-action-collapse='{"target": ".panel-body"}'></div>
                    </div>
                    {!! Form::open(['route'=>'betting.vendedor.store', 'method' => "POST", 'id' => 'formVendedor', 'class' => 'form-horizontal row-border','enctype' => 'multipart/form-data']) !!}
                    <div class="panel-body">
                        @include('tamplatesForms.tamplateFormVendedor')
                    </div>
                    <div class="panel-footer">
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>

@endsection

@section('js')
    @parent
    <script type="text/javascript" src="{{ asset('/js/validacoes/validation_form_vendedor.js')}}"></script>
    <script type="text/javascript">
        var elem = document.querySelector('.js-switch-info');
        var init = new Switchery(elem);
    </script>
@endsection

resources/views/vendedor/edit.blade.php
@extends('menu')

@section('css')
    @parent
    <style>
        .form-group {
            margin-top: -10px;;
        }
        .table-responsive {
            min-height: 0.01%;
            overflow-x: initial;
        }
    </style>
@endsection

@section('page-heading')
    <h1>Vendedores</h1>
@endsection

@section('container')

    <div data-widget-group="group1">
        <div class="row">
            <div class="col-sm-12">

                @if(Session::has('message'))
                    <div class="alert alert-success">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <em> {!! session('message') !!}</em>
                    </div>
                @endif

                @if(Session::has('errors'))
                    <div class="alert alert-danger">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        @foreach($errors->all() as $error)
                            <div>{{ $error }}</div>
                        @endforeach
                    </div>
                @endif

                <div class="panel panel-default" data-widget='{"draggable": "false"}'>
                    <div class="panel-heading">
                        <h2>Editar vendedor</h2>
                        <div class="panel-ctrls" data-actions-container=""
                             data-action-collapse='{"target": ".panel-body"}'></div>
                    </div>

                    <div class="panel-body">
                        @include('tamplatesForms.tamplateFormVendedorEdit')
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('js')
    @parent
    <script type="text/javascript" src="{{ asset('/js/validacoes/validation_form_vendedorEdit.js')}}"></script>
    <script type="text/javascript">
        var idConfigVendas = 0;
        var table = $('#confg-grid').DataTable({
            processing: true,
            serverSide: true,
            ajax: {
                url: "{{ route('betting.vendedor.gridConfig', ['id' => $model->id]) }}",
                method: 'POST'
            },
            language: {
                "lengthMenu": "_MENU_",
                "zeroRecords": "Não foram encontrados resultados",
                "info": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                "infoEmpty": "Mostrando de 0 até 0 de 0 registros",
                "infoFiltered": "(Filtrado de _MAX_ total de registro)",
                "sProcessing":   "Processando...",
                "oPaginate": {
                    "sFirst":    "Primeiro",
                    "sPrevious": "Anterior",
                    "sNext":     "Seguinte",
                    "sLast":     "Último"
                }
            },
            columns: [
                {data: 'vendas', name: 'conf_vendas.limite_vendas'},
                {data: 'comissao', name: 'conf_vendas.comissao'},
                {data: 'cotacao', name: 'conf_vendas.cotacao'},
                {data: 'tipo', name: 'tipo_cotacao.nome'},
                {data: 'status', name: 'status.nome'},
                {data: 'data', name: 'conf_vendas.data'},
                {data: 'total', name: 'vendas.valor_total', orderable: false, searchable: false},
                {data: 'action', name: 'action', orderable: false, searchable: false}
            ]
        });
        $('.dataTables_filter input').attr('placeholder','Pesquisar...');

        //Retonra da tabela os registro pertencentes a linha selecionada
        $('#confg-grid tbody').on( 'click', '.edit', function (event) {
            event.preventDefault();

            //validando se uma linha da tabela foi selecioando ou não
            if ($(this).parent().parent().hasClass('selected')) {
                $(this).parent().parent().removeClass('selected');
            }
            else {
                table.$('tr.selected').removeClass('selected');
                $(this).parent().parent().addClass('selected');
            }

            //se a linha foi selecionada, recuperace os dados da mesma
            var data = table.rows('.selected').data()[0];

            //Preenchendo os campos dos formulário para edição
            $('#limite').val(data['vendas']);
            $('#comissao').val(data['comissao']);
            $('#cotacao').val(data['cotacao']);
            tipoCotacao(data['id_tipo']);
            idConfigVendas = data['id']

            $('.save').prop('disabled', true);
            $('.edit').prop('disabled', false);

        } );

        //salvar configurações do vendedor
        $('.edit').on('click', function(){

            //pegando os campos do formulário
            var limite = $('#limite').val();
            var comissao = $('#comissao').val();
            var cotacao = $('#cotacao').val();
            var tipoCota = $('#tipo_cotacao').val();

            //estrututando os dados do formulário em array para envio ajax
            var dados = {
                'limite_vendas': limite,
                'comissao': comissao,
                'cotacao': cotacao,
                'tipo_cotacao_id': tipoCota,
                'idConfig' : idConfigVendas
            }

            //Validando formulário configuração de vendas edit
            if(limite == "" || comissao == "" || cotacao == "" || tipoCota == "") {
                bootbox.alert('Todos os campos são de preenchimento obrigatório');
            } else {
                jQuery.ajax({
                    type: 'POST',
                    url: '{{route('betting.vendedor.updateConfig')}}',
                    data: dados,
                    datatype: 'json'
                }).done(function (json) {

                    //desabilitando botão salvar e habilitando o botão editar
                    $('.save').prop('disabled', false);
                    $('.edit').prop('disabled', true);

                    //exibindo mensagem retornada pela requisição
                    bootbox.alert(json['msg']);

                    //recarregando a tabela de dados de configuração de vendas
                    table.ajax.reload();

                    //Limpando os campos do formulário após a edição
                    var limite = $('#limite').val("");
                    var comissao = $('#comissao').val("");
                    var cotacao = $('#cotacao').val("");

                    //Recarregando os campo de tipo de cotação
                    tipoCotacao();

                });
            }

        });

        //Validando formulário configuração de vendas save
        $('#formConfig').submit(function(event){

            //pegando os campos do formulário
            var limite = $('#limite').val();
            var comissao = $('#comissao').val();
            var cotacao = $('#cotacao').val();
            var tipoCota = $('#tipo_cotacao').val();

            //Validando formulário configuração de vendas salvar
            if(limite == "" || comissao == "" || cotacao == "" || tipoCota == "") {
                bootbox.alert('Todos os campos são de preenchimento obrigatório');
                return false;
            } else {
                return true;
            }
        });

        //Função para listar as localidades
        function tipoCotacao(id) {
            jQuery.ajax({
                type: 'POST',
                url: '{{ route('betting.allTipoCotacao')  }}',
                datatype: 'json',
            }).done(function (json) {
                var option = '';
                for (var i = 0; i < json['tipoCotacaoes'].length; i++) {
                    if (json['tipoCotacaoes'][i]['id'] == id) {
                        option += '<option selected value="' + json['tipoCotacaoes'][i]['id'] + '">' + json['tipoCotacaoes'][i]['nome'] + '</option>';
                    } else {
                        option += '<option value="' + json['tipoCotacaoes'][i]['id'] + '">' + json['tipoCotacaoes'][i]['nome'] + '</option>';
                    }
                }
                $('#tipo_cotacao option').remove();
                $('#tipo_cotacao').append(option);
            });
        }

    </script>
@endsection

resources/views/vendedor/index.blade.php
@extends('menu')

@section('css')
    @parent
<style>
    .table-responsive {
        min-height: 0.01%;
        overflow-x: initial;
    }
</style>
@endsection

@section('page-heading')
    <h1>Vendedor</h1>
@endsection

@section('container')

    <div data-widget-group="group1">
        <div class="row">
            <div class="col-sm-12">
                @if(Session::has('message'))
                    <div class="alert alert-success">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <em> {!! session('message') !!}</em>
                    </div>
                @endif

                @if(Session::has('errors'))
                    <div class="alert alert-danger">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        @foreach($errors->all() as $error)
                            <div>{{ $error }}</div>
                        @endforeach
                    </div>
                @endif

                <div class="panel panel-default" data-widget='{"draggable": "false"}'>
                    <div class="panel-heading">
                        <h2>Lista de vendedores</h2><br />

                        @permission('vendedor.create')
                        <a href="{{ route('betting.vendedor.create')}}" class="btn btn-primary">Novo Vendedor</a>
                        @endpermission

                        <div class="panel-ctrls" data-actions-container=""
                             data-action-collapse='{"target": ".panel-body"}'></div>
                    </div>

                    <div class="panel-body">
                        <div class="table-responsive no-padding">
                            <table id="area-grid" class="display table table-bordered" cellspacing="0" width="100%">
                                <thead>
                                <tr>
                                    <th>Código</th>
                                    <th>Área</th>
                                    <th>Nome</th>
                                    <th>Usuário</th>
                                    <th>Estorno</th>
                                    <th>Ativo</th>
                                    <th>Limite de vendas</th>
                                    <th>Total de vendas</th>
                                    <th>Comissão</th>
                                    <th>Cotação</th>
                                    <th>Acão</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>Código</th>
                                    <th>Área</th>
                                    <th>Nome</th>
                                    <th>Usuário</th>
                                    <th>Estorno</th>
                                    <th>Ativo</th>
                                    <th>Limite de vendas</th>
                                    <th>Total de vendas</th>
                                    <th>Comissão</th>
                                    <th>Cotação</th>
                                    <th style="width: 15%;">Acão</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

@endsection

@section('js')
    @parent
    <script type="text/javascript">

        var table = $('#area-grid').DataTable({
            processing: true,
            serverSide: true,
            ajax: {
                url: "{!! route('betting.vendedor.grid') !!}",
                method: 'POST'
            },
            language: {
                "lengthMenu": "_MENU_",
                "zeroRecords": "Não foram encontrados resultados",
                "info": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                "infoEmpty": "Mostrando de 0 até 0 de 0 registros",
                "infoFiltered": "(Filtrado de _MAX_ total de registro)",
                "sProcessing":   "Processando...",
                "oPaginate": {
                    "sFirst":    "Primeiro",
                    "sPrevious": "Anterior",
                    "sNext":     "Seguinte",
                    "sLast":     "Último"
                }
            },
            columns: [
                {data: 'codigo', name: 'pessoas.codigo'},
                {data: 'nome_area', name: 'areas.nome'},
                {data: 'nome', name: 'pessoas.nome'},
                {data: 'usuario', name: 'pessoas.usuario'},
                {data: 'estorno', name: 'estorno_vendedor.nome'},
                {data: 'status', name: 'status.nome'},
                {data: 'limite', name: 'conf_vendas.limite_vendas'},
                {data: 'valor_total', name: 'vendas.valor_total', orderable: false, searchable: false},
                {data: 'comissao', name: 'conf_vendas.comissao'},
                {data: 'cotacao', name: 'conf_vendas.cotacao'},
                {data: 'action', name: 'action', orderable: false, searchable: false}
            ]
        });

        $('.dataTables_filter input').attr('placeholder','Pesquisar...');

        //DOM Manipulation to move datatable elements integrate to panel
        $('.panel-ctrls').append($('.dataTables_filter').addClass("pull-right")).find("label").addClass("panel-ctrls-center");
        $('.panel-ctrls').append("<i class='separator'></i>");
        $('.panel-ctrls').append($('.dataTables_length').addClass("pull-left")).find("label").addClass("panel-ctrls-center");

        $('.panel-footer').append($(".dataTable+.row"));
        $('.dataTables_paginate>ul.pagination').addClass("pull-right m-n");

        $(document).on('click', 'a.zerar', function (event) {
            event.preventDefault();
            var url = $(this).attr('href');
            bootbox.confirm("Tem certeza que deseja zerar o limite?", function (result) {
                if (result) {
                    location.href = url
                } else {
                    false;
                }
            });
        });

    </script>
@endsection