app/Http/routes.php
<?php

Route::group(['prefix' => LaravelLocalization::setLocale()], function () {

    Route::group(['prefix' => 'auth'], function () {
        Route::get('login', 'Auth\AuthController@getLogin');
        Route::post('login', 'Auth\AuthController@postLogin');
        Route::get('logout', 'Auth\AuthController@getLogout');
    });

    Route::group(['prefix' => 'betting', 'middleware' => 'auth', 'as' => 'betting.'], function () {
//    Route::get('login'  , ['as' => 'login', 'uses' => 'SecurityController@login']);
//    Route::get('logout'  , ['as' => 'logout', 'uses' => 'SecurityController@logout']);
//    Route::post('check'  , ['as' => 'check', 'uses' => 'SecurityController@check']);
//    Route::get('index'  , ['as' => 'index', 'middleware'=>'security:ROLE_ADMIN', 'uses' => 'DefaultController@index']);
//    Route::get('update2'  , ['as' => 'update2', 'middleware'=>'security:ROLE_ADMIN', 'uses' => 'DefaultController@update2']);

        Route::get('index'  , ['as' => 'index', 'uses' => 'DefaultController@index']);

        //Rotas para Dashboard
        Route::post('dashboard'  , ['as' => 'dashboard', 'uses' => 'DefaultController@dashboard']);
        Route::post('resultVendas'  , ['as' => 'resultVendas', 'uses' => 'DefaultController@resultadosVendas']);

        //Rotas para sete da sorte
        Route::get('seteSorte'  , ['as' => 'seteSorte', 'uses' => 'SeteSorteController@index']);
        Route::post('seteGrid'  , ['as' => 'seteGrid', 'uses' => 'SeteSorteController@dashboard']);
        Route::post('resultVendasST'  , ['as' => 'resultVendasST', 'uses' => 'SeteSorteController@resultadosVendas']);

        //Rotas para selectes via ajax
        Route::post('allTipoCotacao'  , ['as' => 'allTipoCotacao', 'uses' => 'DefaultController@allTipoCotacao']);

        Route::group(['prefix' => 'parametro', 'as' => 'parametro.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'ParametrosController@index']);
            Route::get('grid', ['as' => 'grid', 'uses' => 'ParametrosController@grid']);
            Route::get('create', ['as' => 'create', 'uses' => 'ParametrosController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'ParametrosController@store']);
            Route::get('save', ['middleware' => 'permission:parametro.update', 'as' => 'save', 'uses' => 'ParametrosController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'ParametrosController@update']);
        });

        Route::group(['prefix' => 'area', 'as' => 'area.'], function () {
            Route::get('index', ['middleware' => 'permission:area.select', 'as' => 'index', 'uses' => 'AreasController@index']);
            Route::post('grid', ['as' => 'grid', 'uses' => 'AreasController@grid']);
            Route::get('create', ['middleware' => 'permission:area.create', 'as' => 'create', 'uses' => 'AreasController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'AreasController@store']);
            Route::get('edit/{id}', ['middleware' => 'permission:area.update', 'as' => 'edit', 'uses' => 'AreasController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'AreasController@update']);
            Route::get('delete/{id}', ['middleware' => 'permission:area.destroy', 'as' => 'delete', 'uses' => 'AreasController@delete']);
        });

        Route::group(['prefix' => 'vendedor', 'as' => 'vendedor.'], function () {
            Route::get('index', ['middleware' => 'permission:vendedor.select', 'as' => 'index', 'uses' => 'VendedorController@index']);
            Route::post('grid', ['as' => 'grid', 'uses' => 'VendedorController@grid']);
            Route::post('gridConfig/{id}', ['as' => 'gridConfig', 'uses' => 'VendedorController@gridConfig']);
            Route::get('create', ['middleware' => 'permission:vendedor.create', 'as' => 'create', 'uses' => 'VendedorController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'VendedorController@store']);
            Route::post('storeConfig', ['as' => 'storeConfig', 'uses' => 'VendedorController@storeConfig']);
            Route::get('edit/{id}', ['middleware' => 'permission:vendedor.update', 'as' => 'edit', 'uses' => 'VendedorController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'VendedorController@update']);
            Route::post('updateConfig', ['as' => 'updateConfig', 'uses' => 'VendedorController@updateConfig']);
            Route::get('zerar/{id}', ['as' => 'zerar', 'uses' => 'VendedorController@zerar']);
        });

        Route::group(['prefix' => 'arrecadador', 'as' => 'arrecadador.'], function () {
            Route::get('index', ['middleware' => 'permission:arrecadador.select', 'as' => 'index', 'uses' => 'ArrecadadorController@index']);
            Route::post('grid', ['as' => 'grid', 'uses' => 'ArrecadadorController@grid']);
            Route::get('create', ['middleware' => 'permission:arrecadador.create', 'as' => 'create', 'uses' => 'ArrecadadorController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'ArrecadadorController@store']);
            Route::get('edit/{id}', ['middleware' => 'permission:arrecadador.update', 'as' => 'edit', 'uses' => 'ArrecadadorController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'ArrecadadorController@update']);
            Route::get('delete/{id}', ['middleware' => 'permission:arrecadador.destroy', 'as' => 'delete', 'uses' => 'ArrecadadorController@delete']);
        });

        # Rota para as partidas
        Route::group(['prefix' => 'partidas', 'as' => 'partidas.'], function () {
            Route::get('index', ['middleware' => 'permission:partida.select', 'as' => 'index', 'uses' => 'PartidasController@index']);
            Route::post('grid', ['as' => 'grid', 'uses' => 'PartidasController@grid']);
            Route::get('create', ['middleware' => 'permission:partida.create', 'as' => 'create', 'uses' => 'PartidasController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'PartidasController@store']);
            Route::get('edit/{id}', ['middleware' => 'permission:partida.update', 'as' => 'edit', 'uses' => 'PartidasController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'PartidasController@update']);
            Route::get('destroy/{id}', ['middleware' => 'permission:partida.destroy', 'as' => 'edit', 'uses' => 'PartidasController@destroy']);
            Route::get('getPartidas', ['as' => 'getPartidas', 'uses' => 'PartidasController@getPartidas']);
            Route::get('getPartidasSemApostas', ['as' => 'getPartidasSemApostas', 'uses' => 'PartidasController@getPartidasSemApostas']);
        });

        # Rota para as modalidades
        Route::group(['prefix' => 'modalidades', 'as' => 'modalidades.'], function () {
            Route::get('index', ['middleware' => 'permission:modalidade.select', 'as' => 'index', 'uses' => 'ModalidadesController@index']);
            Route::post('grid', ['as' => 'grid', 'uses' => 'ModalidadesController@grid']);
            Route::get('create', ['middleware' => 'permission:modalidade.create', 'as' => 'create', 'uses' => 'ModalidadesController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'ModalidadesController@store']);
            Route::get('edit/{id}', ['middleware' => 'permission:modalidade.update', 'as' => 'edit', 'uses' => 'ModalidadesController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'ModalidadesController@update']);
            Route::get('destroy/{id}', ['middleware' => 'permission:modalidade.destroy', 'as' => 'edit', 'uses' => 'ModalidadesController@destroy']);
            Route::get('getModalidade/{id}', ['as' => 'getModalidade', 'uses' => 'ModalidadesController@getModalidade']);
        });

        # Rota para as cotações
        Route::group(['prefix' => 'cotacoes', 'as' => 'cotacoes.'], function () {
            Route::get('index', ['middleware' => 'permission:cotacao.select', 'as' => 'index', 'uses' => 'CotacoesController@index']);
            Route::post('grid', ['as' => 'grid', 'uses' => 'CotacoesController@grid']);
            Route::get('create', ['middleware' => 'permission:cotacao.create', 'as' => 'create', 'uses' => 'CotacoesController@create']);
            Route::get('createMultiplo', ['as' => 'createMultiplo', 'uses' => 'CotacoesController@createMultiplo']);
            Route::post('store', ['as' => 'store', 'uses' => 'CotacoesController@store']);
            Route::post('storeMultiplo', ['as' => 'storeMultiplo', 'uses' => 'CotacoesController@storeMultiplo']);
            Route::get('edit/{id}', ['middleware' => 'permission:cotacao.update', 'as' => 'edit', 'uses' => 'CotacoesController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'CotacoesController@update']);
            Route::get('destroy/{id}', ['middleware' => 'permission:cotacao.destroy', 'as' => 'edit', 'uses' => 'CotacoesController@destroy']);
        });

        # Rota para gols
        Route::group(['prefix' => 'gols', 'as' => 'gols.'], function () {
            Route::get('index', ['middleware' => 'permission:resultado.select', 'as' => 'index', 'uses' => 'GolsController@index']);
            Route::post('grid/{idPartida}', ['as' => 'grid', 'uses' => 'GolsController@grid']);
            Route::get('create', ['as' => 'create', 'uses' => 'GolsController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'GolsController@store']);
            Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'GolsController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'GolsController@update']);
            Route::delete('delete/{id}', ['as' => 'delete', 'uses' => 'GolsController@destroy']);
            Route::get('getTimes', ['as' => 'getTimes', 'uses' => 'GolsController@getTimes']);

app/Http/Controllers/DefaultController.php
<?php

namespace Softage\Http\Controllers;

use Illuminate\Http\Request;

use Softage\Http\Requests;
use Softage\Http\Controllers\Controller;
use Softage\Repositories\TipoCotacaoRepository;
use Yajra\Datatables\Datatables;
use Softage\Uteis\SerbinarioDateFormat;

class DefaultController extends Controller
{

    /**
     * @var TipoCotacaoRepository
     */
    private $TipoCotacaoRepository;
    
    /**
     * DefaultController constructor.
     * @param TipoCotacaoRepository $TipoCotacaoRepository
     */
    public function __construct(TipoCotacaoRepository $TipoCotacaoRepository)
    {
        $this->TipoCotacaoRepository = $TipoCotacaoRepository;
    }
    
    public function index()
    {
        return view('default.index');
    }

    public function allTipoCotacao()
    {
        
        $tipoCotacaoes = $this->TipoCotacaoRepository->all();
        
        return compact('tipoCotacaoes');
    }

    /**
     * @param Request $request
     * @return mixed
     */
    public function dashboard(Request $request)
    {

        $dados = $request->request->all();
        
        if(isset($dados['searchDate']) && $dados['searchDate'] != "") {
            $data = SerbinarioDateFormat::toUsa($dados['searchDate'], 'date');
        } else {
            $dateObj = new \DateTime('now');
            $data = $dateObj->format('Y-m-d');
        }

        #Criando a consulta de Gols
        $rows = \DB::table('partidas')
            ->join('times as time_casa', 'time_casa.id', '=', 'partidas.time_casa_id')
            ->join('times as time_fora', 'time_fora.id', '=', 'partidas.time_fora_id')
            ->join('campeonatos', 'campeonatos.id', '=', 'partidas.campeonato_id')
            ->leftJoin('processadas', 'processadas.id', '=', 'partidas.processada_id')
            ->whereDate('partidas.data', '=', $data)
            ->select([
                'partidas.id as id',
                \DB::raw("concat(time_casa.nome,' x ',time_fora.nome) as partida"),
                'campeonatos.nome as campeonato',
                'partidas.hora as hora',
                'processadas.nome as status',
                'processadas.id as status_id',
            ]);

        #Editando a grid
        return Datatables::of($rows)
            ->addColumn('qtdApostas', function ($row) {

                $q1 = \DB::table('apostas')
                    ->join('partidas', 'partidas.id', '=', 'apostas.partida_id')
                    ->join('vendas', 'vendas.id', '=', 'apostas.venda_id')
                    ->groupBy('partidas.id')
                    ->where('vendas.status_v_id', '=', '1')
                    ->where('partidas.id', '=', $row->id)
                    ->select([
                        \DB::raw("count(apostas.id) as qtd_apostas"),
                    ])->first();

                if (count($q1) > 0) {
                    return $q1->qtd_apostas;
                } else {
                    return "";
                }

            })
            ->addColumn('casa', function ($row) {

            $q1 = \DB::table('cotacoes')
                ->join('partidas', 'partidas.id', '=', 'cotacoes.partida_id')
                ->join('modalidades', 'modalidades.id', '=', 'cotacoes.modalidade_id')
                ->where('modalidades.t_casa', '=', 'true')
                ->where('partidas.id', '=', $row->id)
                ->select('cotacoes.valor')->first();

            if (count($q1) > 0) {
                return $q1->valor;
            } else {
                return "";
            }

        })
            ->addColumn('fora', function ($row) {

                $q1 = \DB::table('cotacoes')
                    ->join('partidas', 'partidas.id', '=', 'cotacoes.partida_id')
                    ->join('modalidades', 'modalidades.id', '=', 'cotacoes.modalidade_id')
                    ->where('modalidades.t_fora', '=', 'true')
                    ->where('partidas.id', '=', $row->id)
                    ->select('cotacoes.valor')->first();

                if (count($q1) > 0) {
                    return $q1->valor;
                } else {
                    return "";
                }

            })
            ->addColumn('empate', function ($row) {

                $q1 = \DB::table('cotacoes')
                    ->join('partidas', 'partidas.id', '=', 'cotacoes.partida_id')
                    ->join('modalidades', 'modalidades.id', '=', 'cotacoes.modalidade_id')
                    ->where('modalidades.t_empate', '=', 'true')
                    ->where('partidas.id', '=', $row->id)
                    ->select('cotacoes.valor')->first();

                if (count($q1) > 0) {
                    return $q1->valor;
                } else {
                    return "";
                }

            })->make(true);
    }

    /**
     * @param Request $request
     * @return array
     */
    public function resultadosVendas(Request $request)
    {
        $dados = $request->request->all();

        if(isset($dados['searchDate']) && $dados['searchDate'] != "") {
            $data = SerbinarioDateFormat::toUsa($dados['searchDate'], 'date');
        } else {
            $dateObj = new \DateTime('now');
            $data = $dateObj->format('Y-m-d');
        }

        $vendasRealizadas = \DB::table('vendas')
            ->join('status_vendas', 'status_vendas.id', '=', 'vendas.status_v_id')
            ->where('vendas.status_v_id', '=', '1')
            ->whereDate('vendas.data', '=', $data)
            ->select([
                \DB::raw("count(vendas.id) as vendas_r"),
            ])->get();

        $vendasCanceladas = \DB::table('vendas')
            ->join('status_vendas', 'status_vendas.id', '=', 'vendas.status_v_id')
            ->where('vendas.status_v_id', '=', '2')
            ->whereDate('vendas.data', '=', $data)
            ->select([
                \DB::raw("count(vendas.id) as vendas_c"),
            ])->get();

        return array('vendas_r' => $vendasRealizadas, 'vendas_c' => $vendasCanceladas);
    }
}

resources/views/default/index.blade.php
@extends('menu')

@section('title')
    @parent
    HOME
@endsection

@section('css')
    @parent
    <style>
        .form-group {
            margin-top: -10px;;
        }
        .table-responsive {
            min-height: 0.01%;
            overflow-x: initial;
        }
    </style>
@endsection

@section('page-heading')
    <h1>Dashboard</h1>
@endsection

@section('container')

    <div data-widget-group="group1">
        <div class="row">
            <div class="col-sm-12">
                {{--<div class="alert alert-info alert-dismissable ">
                    <i class="ti ti-info-alt"></i> Resize the browser window to see the responive tables in action!
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                </div>--}}

                <div class="panel panel-default" data-widget='{"draggable": "false"}'>
                    <div class="panel-heading">
                        <h2>Dashboard</h2>
                        <div class="panel-ctrls" data-actions-container=""
                             data-action-collapse='{"target": ".panel-body"}'></div>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-6">
                                <form role="form" class="form-horizontal">
                                    <div class="form-group">
                                        <div class="col-sm-6">
                                            <div class="input-group" style="margin-top: 80px">
                                                <input style="margin-left: 8px" placeholder="Data" class="form-control mask datepicker" data-inputmask="'alias': 'date'" type="text"
                                                       id="searchDate" name="searchDate">
                                                <div class="input-group-btn">
                                                    <button class="btn btn-info" id="btnSearch" type="button">Buscar</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <div class="col-md-6">
                                <div class="container-fluid">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="info-tile info-tile-alt tile-success">
                                                <div class="tile-icon"><i class="ti ti-check-box"></i></div>
                                                <div class="tile-heading"><span>Vendas realizadas</span></div>
                                                <div class="tile-body"><span id="vendas-r"></span></div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="info-tile info-tile-alt tile-danger">
                                                <div class="tile-icon"><i class="ti  ti-close"></i></div>
                                                <div class="tile-heading"><span>Vendas canceladas</span></div>
                                                <div class="tile-body"><span id="vendas-c"></span></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="table-responsive no-padding">
                                    <table id="dashboard-grid" class="display table table-bordered" cellspacing="0" width="100%">
                                        <thead>
                                        <tr>
                                            <th>Tabela</th>
                                            <th>Hora</th>
                                            <th>Partida</th>
                                            <th>Processada</th>
                                            <th>Apostas</th>
                                            <th>Casa</th>
                                            <th>Fora</th>
                                            <th>Empate</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        </tbody>
                                        <tfoot>
                                        <tr>
                                            <th style="width: 25%">Tabela</th>
                                            <th style="width: 7%">Hora</th>
                                            <th>Partida</th>
                                            <th style="width: 10%">Processada</th>
                                            <th style="width: 8%">Apostas</th>
                                            <th style="width: 6%">Casa</th>
                                            <th style="width: 6%">Fora</th>
                                            <th style="width: 7%">Empate</th>
                                        </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('js')
    @parent
    <script type="text/javascript">

        var table = $('#dashboard-grid').DataTable({
            processing: true,
            serverSide: true,
            iDisplayLength: 20,
            bLengthChange: false,
            bFilter: false,
            fnRowCallback: function( nRow, aData, iDisplayIndex, iDisplayIndexFull ) {
                if ( aData['status_id'] == "1" )
                {
                    $('td', nRow).css('background-color', 'Orange');
                }
            },
            ajax: {
                url: "{!! route('betting.dashboard') !!}",
                method: 'POST',
                data: function (d) {
                    d.searchDate = $('input[name=searchDate]').val();
                }
            },
            language: {
                "lengthMenu": "_MENU_",
                "zeroRecords": "Não foram encontrados resultados",
                "info": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                "infoEmpty": "Mostrando de 0 até 0 de 0 registros",
                "infoFiltered": "(Filtrado de _MAX_ total de registro)",
                "sProcessing":   "Processando...",
                "oPaginate": {
                    "sFirst":    "Primeiro",
                    "sPrevious": "Anterior",
                    "sNext":     "Seguinte",
                    "sLast":     "Último"
                }
            },
            columns: [
                {data: 'campeonato', name: 'campeonatos.nome'},
                {data: 'hora', name: 'partidas.hora'},
                {data: 'partida', name: 'partida'},
                {data: 'status', name: 'processadas.nome'},
                {data: 'qtdApostas', name: 'qtdApostas', orderable: false, searchable: false},
                {data: 'casa', name: 'casa', orderable: false, searchable: false},
                {data: 'fora', name: 'fora', orderable: false, searchable: false},
                {data: 'empate', name: 'empate', orderable: false, searchable: false}
            ]
        });

        //Pega o resultado das vendas
        resultadoVendas();

        // Função do submit do search da grid principal
        $('#btnSearch').click(function(e) {
            table.draw();

            //Pega o resultado das vendas
            resultadoVendas();

            e.preventDefault();
        });

        //Função para trazer o resultado das vendas
        function resultadoVendas()
        {
            var searchData = {
                'searchDate' : $('input[name=searchDate]').val()
            };

            // Requisição ajax
            jQuery.ajax({
                type: 'POST',
                url: "{!! route('betting.resultVendas') !!}",
                data: searchData,
                datatype: 'json'
            }).done(function (jsonResponse) {

                    $('#vendas-r').text(jsonResponse['vendas_r'][0]['vendas_r']);
                    $('#vendas-c').text(jsonResponse['vendas_c'][0]['vendas_c']);

            });
        }

        $('.dataTables_filter input').attr('placeholder', 'Pesquisar...');

    </script>
@endsection