app/Http/routes.php
<?php

Route::group(['prefix' => LaravelLocalization::setLocale()], function () {

    Route::group(['prefix' => 'auth'], function () {
        Route::get('login', 'Auth\AuthController@getLogin');
        Route::post('login', 'Auth\AuthController@postLogin');
        Route::get('logout', 'Auth\AuthController@getLogout');
    });

    Route::group(['prefix' => 'betting', 'middleware' => 'auth', 'as' => 'betting.'], function () {
//    Route::get('login'  , ['as' => 'login', 'uses' => 'SecurityController@login']);
//    Route::get('logout'  , ['as' => 'logout', 'uses' => 'SecurityController@logout']);
//    Route::post('check'  , ['as' => 'check', 'uses' => 'SecurityController@check']);
//    Route::get('index'  , ['as' => 'index', 'middleware'=>'security:ROLE_ADMIN', 'uses' => 'DefaultController@index']);
//    Route::get('update2'  , ['as' => 'update2', 'middleware'=>'security:ROLE_ADMIN', 'uses' => 'DefaultController@update2']);

        Route::get('index'  , ['as' => 'index', 'uses' => 'DefaultController@index']);

        //Rotas para Dashboard
        Route::post('dashboard'  , ['as' => 'dashboard', 'uses' => 'DefaultController@dashboard']);
        Route::post('resultVendas'  , ['as' => 'resultVendas', 'uses' => 'DefaultController@resultadosVendas']);

        //Rotas para sete da sorte
        Route::get('seteSorte'  , ['as' => 'seteSorte', 'uses' => 'SeteSorteController@index']);
        Route::post('seteGrid'  , ['as' => 'seteGrid', 'uses' => 'SeteSorteController@dashboard']);
        Route::post('resultVendasST'  , ['as' => 'resultVendasST', 'uses' => 'SeteSorteController@resultadosVendas']);

        //Rotas para selectes via ajax
        Route::post('allTipoCotacao'  , ['as' => 'allTipoCotacao', 'uses' => 'DefaultController@allTipoCotacao']);

        Route::group(['prefix' => 'parametro', 'as' => 'parametro.'], function () {
            Route::get('index', ['as' => 'index', 'uses' => 'ParametrosController@index']);
            Route::get('grid', ['as' => 'grid', 'uses' => 'ParametrosController@grid']);
            Route::get('create', ['as' => 'create', 'uses' => 'ParametrosController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'ParametrosController@store']);
            Route::get('save', ['middleware' => 'permission:parametro.update', 'as' => 'save', 'uses' => 'ParametrosController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'ParametrosController@update']);
        });

        Route::group(['prefix' => 'area', 'as' => 'area.'], function () {
            Route::get('index', ['middleware' => 'permission:area.select', 'as' => 'index', 'uses' => 'AreasController@index']);
            Route::post('grid', ['as' => 'grid', 'uses' => 'AreasController@grid']);
            Route::get('create', ['middleware' => 'permission:area.create', 'as' => 'create', 'uses' => 'AreasController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'AreasController@store']);
            Route::get('edit/{id}', ['middleware' => 'permission:area.update', 'as' => 'edit', 'uses' => 'AreasController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'AreasController@update']);
            Route::get('delete/{id}', ['middleware' => 'permission:area.destroy', 'as' => 'delete', 'uses' => 'AreasController@delete']);
        });

        Route::group(['prefix' => 'vendedor', 'as' => 'vendedor.'], function () {
            Route::get('index', ['middleware' => 'permission:vendedor.select', 'as' => 'index', 'uses' => 'VendedorController@index']);
            Route::post('grid', ['as' => 'grid', 'uses' => 'VendedorController@grid']);
            Route::post('gridConfig/{id}', ['as' => 'gridConfig', 'uses' => 'VendedorController@gridConfig']);
            Route::get('create', ['middleware' => 'permission:vendedor.create', 'as' => 'create', 'uses' => 'VendedorController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'VendedorController@store']);
            Route::post('storeConfig', ['as' => 'storeConfig', 'uses' => 'VendedorController@storeConfig']);
            Route::get('edit/{id}', ['middleware' => 'permission:vendedor.update', 'as' => 'edit', 'uses' => 'VendedorController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'VendedorController@update']);
            Route::post('updateConfig', ['as' => 'updateConfig', 'uses' => 'VendedorController@updateConfig']);
            Route::get('zerar/{id}', ['as' => 'zerar', 'uses' => 'VendedorController@zerar']);
        });

        Route::group(['prefix' => 'arrecadador', 'as' => 'arrecadador.'], function () {
            Route::get('index', ['middleware' => 'permission:arrecadador.select', 'as' => 'index', 'uses' => 'ArrecadadorController@index']);
            Route::post('grid', ['as' => 'grid', 'uses' => 'ArrecadadorController@grid']);
            Route::get('create', ['middleware' => 'permission:arrecadador.create', 'as' => 'create', 'uses' => 'ArrecadadorController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'ArrecadadorController@store']);
            Route::get('edit/{id}', ['middleware' => 'permission:arrecadador.update', 'as' => 'edit', 'uses' => 'ArrecadadorController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'ArrecadadorController@update']);
            Route::get('delete/{id}', ['middleware' => 'permission:arrecadador.destroy', 'as' => 'delete', 'uses' => 'ArrecadadorController@delete']);
        });

        # Rota para as partidas
        Route::group(['prefix' => 'partidas', 'as' => 'partidas.'], function () {
            Route::get('index', ['middleware' => 'permission:partida.select', 'as' => 'index', 'uses' => 'PartidasController@index']);
            Route::post('grid', ['as' => 'grid', 'uses' => 'PartidasController@grid']);
            Route::get('create', ['middleware' => 'permission:partida.create', 'as' => 'create', 'uses' => 'PartidasController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'PartidasController@store']);
            Route::get('edit/{id}', ['middleware' => 'permission:partida.update', 'as' => 'edit', 'uses' => 'PartidasController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'PartidasController@update']);
            Route::get('destroy/{id}', ['middleware' => 'permission:partida.destroy', 'as' => 'edit', 'uses' => 'PartidasController@destroy']);
            Route::get('getPartidas', ['as' => 'getPartidas', 'uses' => 'PartidasController@getPartidas']);
            Route::get('getPartidasSemApostas', ['as' => 'getPartidasSemApostas', 'uses' => 'PartidasController@getPartidasSemApostas']);
        });

        # Rota para as modalidades
        Route::group(['prefix' => 'modalidades', 'as' => 'modalidades.'], function () {
            Route::get('index', ['middleware' => 'permission:modalidade.select', 'as' => 'index', 'uses' => 'ModalidadesController@index']);
            Route::post('grid', ['as' => 'grid', 'uses' => 'ModalidadesController@grid']);
            Route::get('create', ['middleware' => 'permission:modalidade.create', 'as' => 'create', 'uses' => 'ModalidadesController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'ModalidadesController@store']);
            Route::get('edit/{id}', ['middleware' => 'permission:modalidade.update', 'as' => 'edit', 'uses' => 'ModalidadesController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'ModalidadesController@update']);
            Route::get('destroy/{id}', ['middleware' => 'permission:modalidade.destroy', 'as' => 'edit', 'uses' => 'ModalidadesController@destroy']);
            Route::get('getModalidade/{id}', ['as' => 'getModalidade', 'uses' => 'ModalidadesController@getModalidade']);
        });

        # Rota para as cotações
        Route::group(['prefix' => 'cotacoes', 'as' => 'cotacoes.'], function () {
            Route::get('index', ['middleware' => 'permission:cotacao.select', 'as' => 'index', 'uses' => 'CotacoesController@index']);
            Route::post('grid', ['as' => 'grid', 'uses' => 'CotacoesController@grid']);
            Route::get('create', ['middleware' => 'permission:cotacao.create', 'as' => 'create', 'uses' => 'CotacoesController@create']);
            Route::get('createMultiplo', ['as' => 'createMultiplo', 'uses' => 'CotacoesController@createMultiplo']);
            Route::post('store', ['as' => 'store', 'uses' => 'CotacoesController@store']);
            Route::post('storeMultiplo', ['as' => 'storeMultiplo', 'uses' => 'CotacoesController@storeMultiplo']);
            Route::get('edit/{id}', ['middleware' => 'permission:cotacao.update', 'as' => 'edit', 'uses' => 'CotacoesController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'CotacoesController@update']);
            Route::get('destroy/{id}', ['middleware' => 'permission:cotacao.destroy', 'as' => 'edit', 'uses' => 'CotacoesController@destroy']);
        });

        # Rota para gols
        Route::group(['prefix' => 'gols', 'as' => 'gols.'], function () {
            Route::get('index', ['middleware' => 'permission:resultado.select', 'as' => 'index', 'uses' => 'GolsController@index']);
            Route::post('grid/{idPartida}', ['as' => 'grid', 'uses' => 'GolsController@grid']);
            Route::get('create', ['as' => 'create', 'uses' => 'GolsController@create']);
            Route::post('store', ['as' => 'store', 'uses' => 'GolsController@store']);
            Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'GolsController@edit']);
            Route::post('update/{id}', ['as' => 'update', 'uses' => 'GolsController@update']);
            Route::delete('delete/{id}', ['as' => 'delete', 'uses' => 'GolsController@destroy']);
            Route::get('getTimes', ['as' => 'getTimes', 'uses' => 'GolsController@getTimes']);

resources/views/tamplatesForms/tamplateFormArea.blade.php
<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div>
                <div class="form-group">
                    {!! Form::label('nome', 'Nome', array('class' => 'col-sm-2 control-label')) !!}
                    <div class="col-sm-5">
                        {!! Form::text('nome', Session::getOldInput('nome')  , array('class' => 'form-control')) !!}
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label label-input-xs">Ativar/Desativar</label>
                    <div class="col-sm-8">
                        <ul class="demo-btns mb-n xs">
                            <li>
                                {!! Form::hidden('status', 0) !!}
                                @if(!isset($model->id))
                                    {!! Form::checkbox('status', 1, null, ['class' => 'js-switch-info switchery-xs', 'checked' => 'checked']) !!}
                                @else
                                    {!! Form::checkbox('status', 1, null, ['class' => 'js-switch-info switchery-xs']) !!}
                                @endif
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section('js')
    @parent
    <script type="text/javascript" src="{{ asset('/js/validacoes/validation_form_area.js')}}"></script>
    <script type="text/javascript">
        var elem = document.querySelector('.js-switch-info');
        var init = new Switchery(elem);
    </script>
@endsection

resources/views/tamplatesForms/tamplateFormChips.blade.php
<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div>
                <div class="form-group">
                    {!! Form::label('nome', 'Número', array('class' => 'col-sm-2 control-label')) !!}
                    <div class="col-sm-5">
                        {!! Form::text('nome', Session::getOldInput('nome')  , array('class' => 'form-control')) !!}
                    </div>
                </div>
                <div class="form-group">
                    {!! Form::label('serial', 'Serial', array('class' => 'col-sm-2 control-label')) !!}
                    <div class="col-sm-5">
                        {!! Form::text('serial', Session::getOldInput('serial')  , array('class' => 'form-control')) !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section('js')
    @parent
    <script type="text/javascript" src="{{ asset('/js/validacoes/validation_form_area.js')}}"></script>
    <script type="text/javascript">
        var elem = document.querySelector('.js-switch-info');
        var init = new Switchery(elem);
    </script>
@endsection

resources/views/tamplatesForms/tamplateFormCotacoes.blade.php
<div class="row">
    <div class="col-md-12">

        <div class="row">
            <div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="searchDate">Data</label>
                    <div class="col-sm-3">
                        <div class="input-group">
                            @if(isset($model->id))
                                <input class="form-control mask" value="{{$model->partida->data}}" data-inputmask="'alias': 'date'" type="text" id="searchDate">
                            @else
                                <input class="form-control mask datepicker" data-inputmask="'alias': 'date'" type="text" id="searchDate">
                            @endif
                            <div class="input-group-btn">
                                <button class="btn btn-info" id="btnSearch" type="button">Buscar</button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    {!! Form::label('partida_id', 'Partida', array('class' => 'col-sm-2 control-label')) !!}
                    <div class="col-sm-3">
                        @if(isset($model->id))
                            {!! Form::select('partida_id', [$model->partida->id => $model->partida->casa->nome . " x " . $model->partida->fora->nome],
                             Session::getOldInput('partida_id'), array('class' => 'form-control')) !!}
                        @else
                            {!! Form::select('partida_id', array(), Session::getOldInput('partida_id'), array('class' => 'form-control')) !!}
                        @endif
                    </div>
                </div>

                <div class="form-group">
                    {!! Form::label('modalidade_id', 'Modalidades', array('class' => 'col-sm-2 control-label')) !!}
                    <div class="col-sm-3">
                        {!! Form::select('modalidade_id', (['' => 'Selecione uma modalidade'] + $loadFields['modalidades']->toArray()), Session::getOldInput('modalidade_id'), array('class' => 'form-control')) !!}
                    </div>
                </div>

                <div class="form-group">
                    {!! Form::label('valor', 'Cotação', array('class' => 'col-sm-2 control-label')) !!}
                    <div class="col-sm-3">
                        {!! Form::text('valor', Session::getOldInput('valor')  , array('class' => 'form-control money')) !!}
                    </div>
                </div>

                <div class="form-group">
                    {!! Form::label('status_id', 'Ativo', array('class' => 'col-sm-2 control-label')) !!}
                    <div class="col-sm-3">
                        {!! Form::select('status_id',  $loadFields2['status'], Session::getOldInput('status_id'), array('class' => 'form-control')) !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section('js')
    @parent
    <script type="text/javascript" src="{{ asset('/js/validacoes/validation_form_cotacao.js')}}"></script>
    <script type="text/javascript" src="{{ asset('js/cotacoes/cotacoes.js')  }}"></script>
    <script type="text/javascript">
        // Evento para bloquear a cotação se caso o valor passado
        // for maior que o limite definido na modalidade
        // Recuperando o id da modalidade
        $('#formCotacao').submit(function (event) {
            event.preventDefault();

            // Recuperando o id da modalidade
            var idModalidade = $('#modalidade_id').find('option:selected').val();

            // Validando a modalidade
            if(idModalidade) {
                // Requisição ajax
                jQuery.ajax({
                    type: 'GET',
                    url: laroute.route('betting.modalidades.getModalidade', {'id' : idModalidade}),
                    datatype: 'json'
                }).done(function (jsonResponse) {

                    if (jsonResponse.success) {
                        // Recuperando o valor da cotação
                        var valorCotacao = $('#valor').val();
                        // Regra de negócio
                        if(parseFloat(valorCotacao) > parseFloat(jsonResponse.data.limite_cotacao)) {

                            // Mensagem
                            bootbox.alert('Valor informado tem que ser menor que o limite estabelecido, limite ' + jsonResponse.data.limite_cotacao);

                            // Matando o processo
                            event.preventDefault();
                        } else {
                            // Encaminhando a requisição
                            $('#formCotacao').unbind('submit').submit()
                        }
                    } else {
                        // Mensagem de retorno caso ocorra algum problema
                        bootbox.alert(jsonResponse.msg);
                    }
                });
            }
        });
    </script>
@endsection

resources/views/tamplatesForms/tamplateFormParametro.blade.php
<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div>
                <div class="form-group">
                    {!! Form::label('nome_banca', 'Nome', array('class' => 'col-sm-2 control-label')) !!}
                    <div class="col-sm-5">
                        {!! Form::text('nome_banca', Session::getOldInput('nome_banca')  , array('class' => 'form-control')) !!}
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label label-input-xs">Nome Da Banca Na Aposta?</label>
                    <div class="col-sm-8">
                        <ul class="demo-btns mb-n xs">
                            <li>
                                {!! Form::hidden('status', 0) !!}
                                {!! Form::checkbox('status', 1, null, ['class' => 'js-switch-info switchery-xs']) !!}
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="form-group">
                    {!! Form::label('mensagem_rodape', 'Mensagem Rodapé', array('class' => 'col-sm-2 control-label')) !!}
                    <div class="col-sm-5">
                        {!! Form::textarea('mensagen_rodape', Session::getOldInput('mensagem_rodape')  ,['size' => '50x3'] , array('class' => 'form-control')) !!}
                    </div>
                </div>
                <div class="form-group">
                    {!! Form::label('limite_premiacao', 'Limite de Premiação', array('class' => 'col-sm-2 control-label')) !!}
                    <div class="col-sm-2">
                        {!! Form::text('limite_premiacao', Session::getOldInput('limite_premiacao')  , array('class' => 'form-control')) !!}
                    </div>
                </div>
                <div class="form-group">
                    {!! Form::label('limite_vendas', 'Limite de vendas', array('class' => 'col-sm-2 control-label')) !!}
                    <div class="col-sm-2">
                        {!! Form::text('limite_vendas', Session::getOldInput('limite_vendas')  , array('class' => 'form-control')) !!}
                    </div>
                </div>
                <div class="form-group">
                    {!! Form::label('premio_sete_da_sorte', 'Premiação sete da sorte', array('class' => 'col-sm-2 control-label')) !!}
                    <div class="col-sm-2">
                        {!! Form::text('premio_sete_da_sorte', Session::getOldInput('premio_sete_da_sorte')  , array('class' => 'form-control')) !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/tamplatesForms/tamplateFormVendedorEdit.blade.php
<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div>
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#principal" data-toggle="tab">Dados principais</a></li>
                    <li><a href="#config" data-toggle="tab">Configuração do vendedor</a></li>
                </ul>

                <div class="tab-content">
                    <div class="tab-pane active" id="principal">
                        <br /><br />
                        {!! Form::model($model, ['route'=> ['betting.vendedor.update', $model->id], 'id' => 'formVendedor', 'class' => 'form-horizontal row-border','enctype' => 'multipart/form-data']) !!}
                        <div class="row">
                            <div class="form-group">
                                {!! Form::label('nome', 'Nome', array('class' => 'col-sm-2 control-label')) !!}
                                <div class="col-sm-8">
                                    {!! Form::text('nome', Session::getOldInput('nome')  , array('class' => 'form-control')) !!}
                                </div>
                            </div>
                            <div class="form-group">
                                {!! Form::label('areas_id', 'Área', array('class' => 'col-sm-2 control-label')) !!}
                                <div class="col-sm-5">
                                    {!! Form::select('area_id', $areas, Session::getOldInput('area_id'), array('class' => 'form-control')) !!}
                                </div>
                            </div>
                            <div class="form-group">
                                {!! Form::label('usuario', 'Usuário', array('class' => 'col-sm-2 control-label')) !!}
                                <div class="col-sm-4">
                                    {!! Form::text('usuario', Session::getOldInput('usuario')  , array('class' => 'form-control')) !!}
                                </div>
                            </div>
                            <div class="form-group">
                                {!! Form::label('senha', 'Senha', array('class' => 'col-sm-2 control-label')) !!}
                                <div class="col-sm-4">
                                    {!! Form::text('senha', Session::getOldInput('senha')  , array('class' => 'form-control')) !!}
                                </div>
                            </div>
                            <div class="form-group">
                                {!! Form::label('status_id', 'Ativo', array('class' => 'col-sm-2 control-label')) !!}
                                <div class="col-sm-2">
                                    {!! Form::select('status_id', $loadFields['status'], Session::getOldInput('status_id'), array('class' => 'form-control')) !!}
                                </div>
                            </div>
                            <div class="form-group">
                                {!! Form::label('estorno_id', 'Estorno', array('class' => 'col-sm-2 control-label')) !!}
                                <div class="col-sm-2">
                                    {!! Form::select('estorno_id', $loadFields['estornovendedor'], Session::getOldInput('estorno_id'), array('class' => 'form-control')) !!}
                                </div>
                            </div>
                            <div class="form-group">
                                {!! Form::label('chipe_id', 'Chipe', array('class' => 'col-sm-2 control-label')) !!}
                                <div class="col-sm-3">
                                    {!! Form::select('chipe_id', (['' => 'Selecione um chipe'] + $loadFields['chipes']->toArray()), Session::getOldInput('chipe_id'), array('class' => 'form-control')) !!}
                                </div>
                            </div>
                            <div class="form-group">
                                {!! Form::label('impressora_id', 'Impressora', array('class' => 'col-sm-2 control-label')) !!}
                                <div class="col-sm-3">
                                    {!! Form::select('impressora_id', (['' => 'Selecione uma impressora'] + $loadFields['impressoras']->toArray()), Session::getOldInput('impressora_id'), array('class' => 'form-control')) !!}
                                </div>
                            </div>
                            <div class="form-group">
                                {!! Form::label('tablet_id', 'Tablet', array('class' => 'col-sm-2 control-label')) !!}
                                <div class="col-sm-3">
                                    {!! Form::select('tablet_id', (['' => 'Selecione um tablet'] + $loadFields['tablets']->toArray()), Session::getOldInput('tablet_id'), array('class' => 'form-control')) !!}
                                </div>
                            </div>
                        </div><br />
                        <div class="row">
                            <div class="col-sm-8 col-sm-offset-2">
                                <button type="submit" class="btn-primary btn" style="margin-left: -11px">Salvar</button>
                                <a class="btn-default btn" href="{{ route('betting.vendedor.index')}}">Voltar</a>
                            </div>
                        </div>{{----}}
                        {!! Form::close() !!}
                    </div>
                    <div class="tab-pane" id="config">
                        <br /><br />
                        {!! Form::open(['route'=>'betting.vendedor.storeConfig', 'method' => "POST", 'id' => 'formConfig', 'class' => 'form-horizontal row-border']) !!}
                        <div class="row">
                            <div class="form-group">
                                {!! Form::label('limite_vendas', 'Limite de vendas', array('class' => 'col-sm-2 control-label ')) !!}
                                <div class="col-sm-3">
                                    {!! Form::text('limite_vendas', null  , array('class' => 'form-control touchspin2 money', 'id' => 'limite')) !!}
                                    {!! Form::hidden('vendedor_id', $model->id , array('class' => 'form-control', 'id' => 'vendedor_id')) !!}
                                </div>
                            </div>

                            <div class="form-group">
                                {!! Form::label('comissao', 'Comissão', array('class' => 'col-sm-2 control-label')) !!}
                                <div class="col-sm-3">
                                    {!! Form::text('comissao', null  , array('class' => 'form-control touchspin2 money', 'id' => 'comissao')) !!}
                                </div>
                            </div>

                            <div class="form-group">
                                {!! Form::label('cotacao', 'Cotação', array('class' => 'col-sm-2 control-label')) !!}
                                <div class="col-sm-3">
                                    {!! Form::text('cotacao', null  , array('class' => 'form-control touchspin1 money', 'id' => 'cotacao')) !!}
                                </div>
                            </div>

                            <div class="form-group">
                                {!! Form::label('tipo_cotacao_id', 'Tipo de cotação', array('class' => 'col-sm-2 control-label')) !!}
                                <div class="col-sm-3">
                                    {!! Form::select('tipo_cotacao_id', $loadFields['tipocotacao'], null, array('class' => 'form-control', 'id' => 'tipo_cotacao')) !!}
                                </div>
                            </div>
                        </div>
                        <br />
                        <div class="row">
                            <div class="col-sm-8 col-sm-offset-2">
                                <button type="submit" class="btn-primary btn save" style="margin-left: -11px">Salvar</button>
                                <button disabled type="button" class="btn-success btn edit">Editar</button>
                                <a class="btn-default btn" href="{{ route('betting.vendedor.index')}}">Voltar</a>
                            </div>
                        </div>
                        {!! Form::close() !!}
                        <br />
                        <div class="row">
                            <div class="col-md-1">
                            </div>
                            <div class="col-md-10">
                                <div class="table-responsive no-padding">
                                    <table id="confg-grid" class="display table table-bordered" cellspacing="0" width="100%">
                                        <thead>
                                        <tr>
                                            <th>Limite de Vendas</th>
                                            <th>Comissão</th>
                                            <th>Cotação</th>
                                            <th>Tipo de cotação</th>
                                            <th>Status</th>
                                            <th>Data</th>
                                            <th>Total Vendido</th>
                                            <th>Acão</th>
                                        </tr>
                                        </thead>
                                        <tfoot>
                                        <tr>
                                            <th>Limite de Vendas</th>
                                            <th>Comissão</th>
                                            <th>Cotação</th>
                                            <th>Tipo de cotação</th>
                                            <th>Status</th>
                                            <th>Data</th>
                                            <th>Total Vendido</th>
                                            <th style="width: 15%;">Acão</th>
                                        </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>